### ISSUE TITLE
Issues with pasting from stdin

### ISSUE THREAD

**Issue by flying-sausages** [pixelfactoryio/privatebin-cli#41]
Heya, I'm trying to make a troubleshooting tool for our toolset and I'm running into this

```
Error: EAGAIN: resource temporarily unavailable, read
    at Object.readSync (fs.js:568:3)
    at tryReadSync (fs.js:353:20)
    at Object.readFileSync (fs.js:390:19)
    at /usr/lib/node_modules/@pixelfactory/privatebin/dist/bin/privatebin.js:54:91436
    at Object.<anonymous> (/usr/lib/node_modules/@pixelfactory/privatebin/dist/bin/privatebin.js:54:91521)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  errno: -11,
  syscall: 'read',
  code: 'EAGAIN'
}
```
When I try to do this

https://github.com/swizzin/swizzin/pull/504/files?file-filters%5B%5D=.sh&file-filters%5B%5D=No+extension#diff-5474d4e7046e9e23e7869da0e81d7fdf3279b580f85fde1a1cd71e475b12c131R30-R40

Do you have any pointers on what I'm doing wrong by any chance? Thanks!

P.s. please make it possible to also specify the password as an argument, otherwise it breaks the stdin support

**Comment by amine7536** [comment]
Hi, i'm not able to reproduce the issue, at least using node 14 and Debian 9 (in a docker container). What node version and os are you using ?

PS: i'll work on passing the password as argument :)

**Comment by amine7536** [comment]
Hi again,

I think your issue is that your `sed` command in `_wash_content()` function never returns (or hangs).

For example this :
```bash
#!/bin/bash

_wash_content() {
    sleep 1
}

_post_content() {
    _wash_content | privatebin send -e 5min -o text >> /tmp/privatebin.log
}

_post_content
``` 

Will raise the error :
```bash
node:internal/fs/utils:313
    throw err;
    ^

Error: EAGAIN: resource temporarily unavailable, read
    at Object.readSync (node:fs:604:3)
    at tryReadSync (node:fs:378:20)
    at Object.readFileSync (node:fs:415:19)
    at /usr/local/lib/node_modules/@pixelfactory/privatebin/dist/bin/privatebin.js:54:91436
    at Object.<anonymous> (/usr/local/lib/node_modules/@pixelfactory/privatebin/dist/bin/privatebin.js:54:91521)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  errno: -11,
  syscall: 'read',
  code: 'EAGAIN'
}
```

**Comment by flying-sausages** [comment]
Sorry for the delay, thanks for the catch! I'll shuffle things around a little, see how I get on.

Do you think it would be worth your time to check this on runtime and catch that error? not sure if it's a standard thing to throw the exception at the user, but depends how often you expect something like this :)
